
modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Stereowalker/C.O.M.B.A.T./issues"
logoFile="Combat.png"
[[mods]]
modId="combat"
version="${file.jarVersion}"#7.3.0-beta"
displayName="C.O.M.B.A.T"
updateJSONURL="https://raw.githubusercontent.com/Stereowalker/My-Home-Page/main/update_files/combat.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/c-o-m-b-a-t"
credits="I'd like to thank my Obsidian Patreon, Komorebi, and you for downloading this mod"
authors="Stereowalker"
description='''
Concept Of Magic, Battle And Technology, or in short, C.O.M.B.A.T, is a mod that aims to adds a whole new sense of exploration to Minecraft
'''
[[dependencies.combat]]
    modId="forge"
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[44,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.combat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.combat]]
    modId="unionlib"
    mandatory=true
    versionRange="[9.0.0, 9.1.0)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.combat]]
    modId="jei"
    mandatory=true
    versionRange="[2.1.0.153,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.combat]]
    modId="terrablender"
    mandatory=true
    versionRange="[2.1.0.134,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.combat]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.3-5.1.4.1,)"
    ordering="NONE"
    side="BOTH"
